version: '3.7'
services:
  pgbackups:
    image: akhilrs/postgres-backup:alpine
    container_name: 'utils.pgbackups'
    restart: always
    volumes:
      - ../db_backups:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 0h5m0s # https://godoc.org/github.com/robfig/cron#hdr-Predefined_schedules
      - BACKUP_KEEP_DAYS=1
      - BACKUP_KEEP_WEEKS=1
      - BACKUP_KEEP_MONTHS=1
      - HEALTHCHECK_PORT=80
      - CLOUD_BACKUP=True
      - CLOUD_PROVIDER=AWS  # Azure or AWS
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - S3_SUB_FOLDER=${S3_SUB_FOLDER}
      - AWS_REGION=${AWS_REGION}
    networks:
      - backend
networks:
  backend: